modera_mjr_security_integration:
    type: annotation
    prefix: '%modera_mjr_integration.routes_prefix%'
    resource: '@ModeraMJRSecurityIntegrationBundle/Controller/'

modera_mjr_security_integration.index.application:
    path: '/%modera_mjr_integration.config.app_name%/Application.js'
    defaults:
        _controller: Modera\MJRSecurityIntegrationBundle\Controller\IndexController::applicationAction

modera_mjr_security_integration.index.is_authenticated:
    path: '/%modera_mjr_integration.config.app_name%/is-authenticated'
    defaults:
        _controller: Modera\MJRSecurityIntegrationBundle\Controller\IndexController::isAuthenticatedAction

modera_mjr_security_integration.index.switch_user_to:
    path: '/%modera_mjr_integration.config.app_name%/switch-user-to/{username}'
    defaults:
        _controller: Modera\MJRSecurityIntegrationBundle\Controller\IndexController::switchUserToAction
